# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cX8L2FVeQqstr1Dz1KusuPdArV-Jrzel
"""

importar  streamlit  como  st
importa  tramamente . expresa  como  px
importar  pandas  como  pd

definición  principal ():
    st . title ( "Gráficos SASSTG" )

    # Creación de un marco de datos
    nombres = [ "ronald" , "david" , "joaquin" , "claudia" , "stefany" , "deysi" , "sofia" , "hugo" , "cesar" , "edwin" , "geraldine" , "enzo" , "dashboards" , "inputs" , "malos" , "querys" , "facturacion" ]
    espacio_completo = [ 23.8 , 203 , 106 , 36.7 , 148 , 6.97 , 3.47 , 0.981 , 0 , 0 , 79.4 , 14.1 , 0.0000011 , 2460 , 21.7 , 0.00828 , 0.216 ]
    espacio_total = [ suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ),
                   suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ),
                   suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ), suma ( espacio_completo ),
                   suma ( espacio_completo ), suma ( espacio_completo )]
    espacio_sastg = [ 3420 , 3420 , 3420 ,3420 , 3420 , 3420 , 3420 , 3420, 3420 , 3420 , 3420, 3420, 3420, 3420 , 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420 , 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420. 3420, 3420, 3420 , 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420, 3420 , 3420 , 3420 , 3420 , 3420 , 3420 , 3420 ]

    df  =  pd . DataFrame ({ 'nombres' : nombres , 'espacio' : espacio_completo , 'espacio_ocupado' : espacio_total , 'espacio_total' : espacio_sastg })
    df [ 'sobrante' ] =  df [ 'espacio_total' ] - df [ 'espacio_ocupado' ]
    df [ 'prc_sobrante' ] =  df [ 'sobrante' ] / df [ 'espacio_total' ]
    df [ 'prc_lleno' ] =  1 - df [ 'prc_sobrante' ]

    # Selector para elegir tipo de gráfico
    chart_type  =  st . selectbox ( "Elegir tipo de gráfico" , ( "Barras" , "Torta" ))

    if  chart_type  ==  "Barras" :
        higo  =  px . bar ( df , y = 'espacio' , x = 'nombres' , text = 'espacio' , color = 'nombres' , title = 'Cantidad de Gigabytes (GB) ocupados en el SASSTG' )
        higo _ update_traces ( plantilla de texto = '%{text:.2s}' , posición de texto = 'fuera' )
        higo _ update_xaxes ( categoría orden = 'total ascendente' )
        higo _ update_layout ( uniformtext_minsize = 5 , xaxis_tickangle = - 60 )

    elif  chart_type  ==  "Torta" :
        higo  =  px . pie ( df , valores = 'espacio' , names = 'nombres' , title = 'Porcentaje de espacio ocupado en SASSTG en Gigabyte (GB)' )
        higo _ update_traces ( posición del texto = 'dentro' , información del texto = 'porcentaje+etiqueta' )

    #Mostrar gráfico
    st . plotly_chart ( fig )

si  __nombre__  ==  '__principal__' :
    principal ()